### ISSUE TITLE
Demo API call not working

### ISSUE THREAD

**Issue by braynm** [shivekkhurana/appuity-frontend#1]
Hi,

 Tried to visit [http://appuity.ml](Demo) when doing API request it request to `localhost:5000/apps/com.zhiliaoapp.musically`

**Comment by shivekkhurana** [comment]
Hi @braynm 

The api is not in production (as you see it made a request to localhost). 

If you want to test the app, you can start the api server using [appuity-api](https://github.com/shivekkhurana/appuity-api) repository.

**Comment by braynm** [comment]
@shivekkhurana Ok, thank you. will close this issue.
