### ISSUE TITLE
Why use absolute paths over relative paths ?

### ISSUE THREAD

**Issue by titxoo** [shivekkhurana/appuity-frontend#2]
Hello m8.

I have a quick question.

Why you did it `import AppLink from 'pages/home/AppLink';` instead of `./home/AppLink';`?

Maybe I don't got the main point about it, any good reason?

**Comment by shivekkhurana** [comment]
I tend to move components around as my app grows in size. 

So Imagine an `AppLink` component that, on day 0, was required only by `home` page. But on day 3 I realised that this component can be generalised and used throughout the app, so it needs to be moved to `components` folder.

`AppLink` also internally depends on a utility to get api base url. If I were to use relative imports then `AppLink` would have an import statement like `import {baseUri} from '../utils/uris'`. And when you change the location of this component, you'd have to change *all* the relative imports. 

To avoid the mess, I use absolute imports everywhere so if the location of the component changes, I only need to change the components that depend on it. 

If you think of it in context of Fractals, you only need to change the children if you use absolute imports, but both parent and child if you use relative imports.

**Comment by shivekkhurana** [comment]
Closing this for now, feel free to reopen if there you have more doubts. 
Thanks
