### ISSUE TITLE
appuity link redirects to video chat website

### ISSUE THREAD

**Issue by hrafnkellbaldurs** [shivekkhurana/appuity-frontend#4]
This website link in the readme [http://appuity.ml](https://github.com/shivekkhurana/appuity-frontend/issues/4) _(I've set the actual link here to this issue to prevent people from opening this)_ redirects you to [http://www.lsl.com/en/](https://github.com/shivekkhurana/appuity-frontend/issues/4) which looks like an adult video chat site, and is definately NSFW.
Please remove this link because this is very misleading.

https://sitecheck.sucuri.net/results/appuity.ml
![image](https://user-images.githubusercontent.com/5609118/68786441-b05bde00-0637-11ea-8cdb-0bab5672e8ab.png)

**Comment by shivekkhurana** [comment]
Thank you for pointing this out. I was on a vacation for the past 15 days and don't know what happened to the website dns. Will move this to github or nowsh soon. 

Have remove links in readme in description as of now.
